namespace: haxney
name: reolink
version: 0.1.0
readme: README.md
description: Ansible collection for managing Reolink IP cameras and NVRs
authors:
  - Dan Hackney <dan@haxney.org>
license:
  - GPL-3.0-or-later
tags:
  - networking
  - security
  - camera
  - reolink
  - iot
repository: https://github.com/haxney/reolink-api-ansible
homepage: https://github.com/haxney/reolink-api-ansible
issues: https://github.com/haxney/reolink-api-ansible/issues
dependencies: {}
